import { Octokit } from '@octokit/rest'

interface Standard {
  id: string; name: string; packageName: string
  description: string; requiredBy: string[]
}

interface Version {
  id: string; version: string; sourceCode: string
  visualSpec: string | null; usageExamples: string | null
  testCases: string | null
}

interface CertificationPRInput {
  standard:       Standard
  version:        Version
  certifierEmail: string
}

function getOctokit(): Octokit {
  const token = process.env.GITHUB_TOKEN
  if (!token) throw new Error('GITHUB_TOKEN not set')
  return new Octokit({ auth: token })
}

function getRepoConfig() {
  return {
    owner: process.env.GITHUB_OWNER ?? 'RGArtStudios',
    repo:  process.env.GITHUB_PLATFORM_REPO ?? 'rg-platform',
  }
}

export async function openCertificationPR(input: CertificationPRInput): Promise<string> {
  const octokit = getOctokit()
  const { owner, repo } = getRepoConfig()
  const { standard, version, certifierEmail } = input

  const pkgDir = standard.packageName.replace('@rg/', '')
  const branch = `standards-studio/${pkgDir}-${version.version}`

  // Get default branch SHA
  const { data: ref } = await octokit.git.getRef({ owner, repo, ref: 'heads/main' })
  const baseSha = ref.object.sha

  // Create branch
  await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha })

  // Update source file
  const srcPath = `packages/${pkgDir}/src/index.ts`
  let existingSha: string | undefined
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path: srcPath, ref: 'main' })
    if (!Array.isArray(data) && 'sha' in data) existingSha = data.sha
  } catch { /* file doesn't exist yet */ }

  await octokit.repos.createOrUpdateFileContents({
    owner, repo, path: srcPath, branch,
    message: `feat(${pkgDir}): update to ${version.version} — certified by ${certifierEmail}`,
    content: Buffer.from(version.sourceCode).toString('base64'),
    ...(existingSha ? { sha: existingSha } : {}),
  })

  // Create PR
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `[Standards Studio] ${standard.name} ${version.version} — Certified`,
    head:  branch,
    base:  'main',
    body:  [
      `## ${standard.name} — ${version.version}`,
      '',
      `**Certified by:** ${certifierEmail}`,
      `**Package:** \`${standard.packageName}\``,
      `**Required by:** ${standard.requiredBy.join(', ')}`,
      '',
      `### Description`,
      standard.description,
      '',
      `### Visual Spec`,
      version.visualSpec ?? '_No visual spec provided_',
      '',
      `### Usage Examples`,
      '```tsx',
      version.usageExamples ?? '// No examples provided',
      '```',
      '',
      `### Test Cases`,
      version.testCases ?? '_No test cases provided_',
      '',
      '---',
      '_This PR was automatically generated by [rg-standards-studio](https://github.com/RGArtStudios/rg-standards-studio)._',
    ].join('\n'),
  })

  return pr.html_url
}
